#!/usr/bin/env python3

from intnum import IntegerToEnglishLatin

if __name__ == '__main__':
    assert str(IntegerToEnglishLatin(0)) == 'zero'
    assert str(IntegerToEnglishLatin(1)) == 'one'
    assert str(IntegerToEnglishLatin(2)) == 'two'
    assert str(IntegerToEnglishLatin(3)) == 'three'
    assert str(IntegerToEnglishLatin(4)) == 'four'
    assert str(IntegerToEnglishLatin(5)) == 'five'
    assert str(IntegerToEnglishLatin(6)) == 'six'
    assert str(IntegerToEnglishLatin(7)) == 'seven'
    assert str(IntegerToEnglishLatin(8)) == 'eight'
    assert str(IntegerToEnglishLatin(9)) == 'nine'
    assert str(IntegerToEnglishLatin(10)) == 'ten'
    assert str(IntegerToEnglishLatin(11)) == 'eleven'
    assert str(IntegerToEnglishLatin(12)) == 'twelve'
    assert str(IntegerToEnglishLatin(13)) == 'thirteen'
    assert str(IntegerToEnglishLatin(14)) == 'fourteen'
    assert str(IntegerToEnglishLatin(15)) == 'fifteen'
    assert str(IntegerToEnglishLatin(16)) == 'sixteen'
    assert str(IntegerToEnglishLatin(17)) == 'seventeen'
    assert str(IntegerToEnglishLatin(18)) == 'eighteen'
    assert str(IntegerToEnglishLatin(19)) == 'nineteen'
    assert str(IntegerToEnglishLatin(20)) == 'twenty'
    assert str(IntegerToEnglishLatin(21)) == 'twenty-one'
    assert str(IntegerToEnglishLatin(22)) == 'twenty-two'
    assert str(IntegerToEnglishLatin(23)) == 'twenty-three'
    assert str(IntegerToEnglishLatin(24)) == 'twenty-four'
    assert str(IntegerToEnglishLatin(25)) == 'twenty-five'
    assert str(IntegerToEnglishLatin(26)) == 'twenty-six'
    assert str(IntegerToEnglishLatin(27)) == 'twenty-seven'
    assert str(IntegerToEnglishLatin(28)) == 'twenty-eight'
    assert str(IntegerToEnglishLatin(29)) == 'twenty-nine'
    assert str(IntegerToEnglishLatin(30)) == 'thirty'
    assert str(IntegerToEnglishLatin(40)) == 'forty'
    assert str(IntegerToEnglishLatin(50)) == 'fifty'
    assert str(IntegerToEnglishLatin(60)) == 'sixty'
    assert str(IntegerToEnglishLatin(70)) == 'seventy'
    assert str(IntegerToEnglishLatin(80)) == 'eighty'
    assert str(IntegerToEnglishLatin(90)) == 'ninety'
    assert str(IntegerToEnglishLatin(100)) == 'one hundred'
    assert str(IntegerToEnglishLatin(10**3)) == 'one thousand'
    assert str(IntegerToEnglishLatin(10**6)) == 'one million'
    assert str(IntegerToEnglishLatin(10**9)) == 'one billion'
    assert str(IntegerToEnglishLatin(10**12)) == 'one trillion'
    assert str(IntegerToEnglishLatin(10**15)) == 'one quadrillion'
    assert str(IntegerToEnglishLatin(10**18)) == 'one quintillion'
    assert str(IntegerToEnglishLatin(10**21)) == 'one sextillion'
    assert str(IntegerToEnglishLatin(10**24)) == 'one septillion'
    assert str(IntegerToEnglishLatin(10**27)) == 'one octillion'
    assert str(IntegerToEnglishLatin(10**30)) == 'one nonillion'
    assert str(IntegerToEnglishLatin(10**33)) == 'one decillion'
    assert str(IntegerToEnglishLatin(10**36)) == 'one undecillion'
    assert str(IntegerToEnglishLatin(10**39)) == 'one duodecillion'
    assert str(IntegerToEnglishLatin(10**42)) == 'one tredecillion'
    assert str(IntegerToEnglishLatin(10**45)) == 'one quattuordecillion'
    assert str(IntegerToEnglishLatin(10**48)) == 'one quindecillion'
    assert str(IntegerToEnglishLatin(10**51)) == 'one sexdecillion'
    assert str(IntegerToEnglishLatin(10**54)) == 'one septendecillion'
    assert str(IntegerToEnglishLatin(10**57)) == 'one octodecillion'
    assert str(IntegerToEnglishLatin(10**60)) == 'one novemdecillion'
    assert str(IntegerToEnglishLatin(10**63)) == 'one vigintillion'
    assert str(IntegerToEnglishLatin(10**66)) == 'one unvigintillion'
    assert str(IntegerToEnglishLatin(10**69)) == 'one duovigintillion'
    assert str(IntegerToEnglishLatin(10**72)) == 'one trevigintillion'
    assert str(IntegerToEnglishLatin(10**75)) == 'one quattuorvigintillion'
    assert str(IntegerToEnglishLatin(10**78)) == 'one quinvigintillion'
    assert str(IntegerToEnglishLatin(10**81)) == 'one sexvigintillion'
    assert str(IntegerToEnglishLatin(10**84)) == 'one septenvigintillion'
    assert str(IntegerToEnglishLatin(10**87)) == 'one octovigintillion'
    assert str(IntegerToEnglishLatin(10**90)) == 'one novemvigintillion'
    assert str(IntegerToEnglishLatin(10**93)) == 'one trigintillion'
    assert str(IntegerToEnglishLatin(10**96)) == 'one untrigintillion'
    assert str(IntegerToEnglishLatin(10**99)) == 'one duotrigintillion'
    assert str(IntegerToEnglishLatin(10**102)) == 'one tretrigintillion'
    assert str(IntegerToEnglishLatin(10**105)) == 'one quattuortrigintillion'
    assert str(IntegerToEnglishLatin(10**108)) == 'one quintrigintillion'
    assert str(IntegerToEnglishLatin(10**111)) == 'one sextrigintillion'
    assert str(IntegerToEnglishLatin(10**114)) == 'one septentrigintillion'
    assert str(IntegerToEnglishLatin(10**117)) == 'one octotrigintillion'
    assert str(IntegerToEnglishLatin(10**120)) == 'one novemtrigintillion'
    assert str(IntegerToEnglishLatin(10**123)) == 'one quadragintillion'
    assert str(IntegerToEnglishLatin(10**153)) == 'one quinquagintillion'
    assert str(IntegerToEnglishLatin(10**183)) == 'one sexagintillion'
    assert str(IntegerToEnglishLatin(10**213)) == 'one septuagintillion'
    assert str(IntegerToEnglishLatin(10**243)) == 'one octogintillion'
    assert str(IntegerToEnglishLatin(10**273)) == 'one nonagintillion'
    assert str(IntegerToEnglishLatin(10**303)) == 'one centillion'
    assert str(IntegerToEnglishLatin(10**312)) == 'one trescentillion'
    assert str(IntegerToEnglishLatin(10**903)) == 'one trecentillion'
    assert str(IntegerToEnglishLatin(10**3003)) == 'one millinillion'
    assert str(IntegerToEnglishLatin(-772813483771722728840176407357132870252343720539632545486182181180375969002426285408120956274643973897)) == 'negative seven hundred seventy-two duotrigintillion eight hundred thirteen untrigintillion four hundred eighty-three trigintillion seven hundred seventy-one novemvigintillion seven hundred twenty-two octovigintillion seven hundred twenty-eight septenvigintillion eight hundred forty sexvigintillion one hundred seventy-six quinvigintillion four hundred seven quattuorvigintillion three hundred fifty-seven trevigintillion one hundred thirty-two duovigintillion eight hundred seventy unvigintillion two hundred fifty-two vigintillion three hundred forty-three novemdecillion seven hundred twenty octodecillion five hundred thirty-nine septendecillion six hundred thirty-two sexdecillion five hundred forty-five quindecillion four hundred eighty-six quattuordecillion one hundred eighty-two tredecillion one hundred eighty-one duodecillion one hundred eighty undecillion three hundred seventy-five decillion nine hundred sixty-nine nonillion two octillion four hundred twenty-six septillion two hundred eighty-five sextillion four hundred eight quintillion one hundred twenty quadrillion nine hundred fifty-six trillion two hundred seventy-four billion six hundred forty-three million nine hundred seventy-three thousand eight hundred ninety-seven'
    assert str(IntegerToEnglishLatin(-5786907833380334209193488109850123772270283030440494562540790958308245791645371738713739648843933287070)) == 'negative five tretrigintillion seven hundred eighty-six duotrigintillion nine hundred seven untrigintillion eight hundred thirty-three trigintillion three hundred eighty novemvigintillion three hundred thirty-four octovigintillion two hundred nine septenvigintillion one hundred ninety-three sexvigintillion four hundred eighty-eight quinvigintillion one hundred nine quattuorvigintillion eight hundred fifty trevigintillion one hundred twenty-three duovigintillion seven hundred seventy-two unvigintillion two hundred seventy vigintillion two hundred eighty-three novemdecillion thirty octodecillion four hundred forty septendecillion four hundred ninety-four sexdecillion five hundred sixty-two quindecillion five hundred forty quattuordecillion seven hundred ninety tredecillion nine hundred fifty-eight duodecillion three hundred eight undecillion two hundred forty-five decillion seven hundred ninety-one nonillion six hundred forty-five octillion three hundred seventy-one septillion seven hundred thirty-eight sextillion seven hundred thirteen quintillion seven hundred thirty-nine quadrillion six hundred forty-eight trillion eight hundred forty-three billion nine hundred thirty-three million two hundred eighty-seven thousand seventy'
    assert str(IntegerToEnglishLatin(-8429509304806846689740701403558508696195856850627303729185549018678388126946645475171984230948287301894)) == 'negative eight tretrigintillion four hundred twenty-nine duotrigintillion five hundred nine untrigintillion three hundred four trigintillion eight hundred six novemvigintillion eight hundred forty-six octovigintillion six hundred eighty-nine septenvigintillion seven hundred forty sexvigintillion seven hundred one quinvigintillion four hundred three quattuorvigintillion five hundred fifty-eight trevigintillion five hundred eight duovigintillion six hundred ninety-six unvigintillion one hundred ninety-five vigintillion eight hundred fifty-six novemdecillion eight hundred fifty octodecillion six hundred twenty-seven septendecillion three hundred three sexdecillion seven hundred twenty-nine quindecillion one hundred eighty-five quattuordecillion five hundred forty-nine tredecillion eighteen duodecillion six hundred seventy-eight undecillion three hundred eighty-eight decillion one hundred twenty-six nonillion nine hundred forty-six octillion six hundred forty-five septillion four hundred seventy-five sextillion one hundred seventy-one quintillion nine hundred eighty-four quadrillion two hundred thirty trillion nine hundred forty-eight billion two hundred eighty-seven million three hundred one thousand eight hundred ninety-four'
    assert str(IntegerToEnglishLatin(8817405800358002672340771631390960283474510886005300428485146825114502942212183012001306422680054928164)) == 'eight tretrigintillion eight hundred seventeen duotrigintillion four hundred five untrigintillion eight hundred trigintillion three hundred fifty-eight novemvigintillion two octovigintillion six hundred seventy-two septenvigintillion three hundred forty sexvigintillion seven hundred seventy-one quinvigintillion six hundred thirty-one quattuorvigintillion three hundred ninety trevigintillion nine hundred sixty duovigintillion two hundred eighty-three unvigintillion four hundred seventy-four vigintillion five hundred ten novemdecillion eight hundred eighty-six octodecillion five septendecillion three hundred sexdecillion four hundred twenty-eight quindecillion four hundred eighty-five quattuordecillion one hundred forty-six tredecillion eight hundred twenty-five duodecillion one hundred fourteen undecillion five hundred two decillion nine hundred forty-two nonillion two hundred twelve octillion one hundred eighty-three septillion twelve sextillion one quintillion three hundred six quadrillion four hundred twenty-two trillion six hundred eighty billion fifty-four million nine hundred twenty-eight thousand one hundred sixty-four'
    assert str(IntegerToEnglishLatin(46327733089287107569823893182817317738252900361088000332693286452975275525138439332647602298250633139)) == 'forty-six duotrigintillion three hundred twenty-seven untrigintillion seven hundred thirty-three trigintillion eighty-nine novemvigintillion two hundred eighty-seven octovigintillion one hundred seven septenvigintillion five hundred sixty-nine sexvigintillion eight hundred twenty-three quinvigintillion eight hundred ninety-three quattuorvigintillion one hundred eighty-two trevigintillion eight hundred seventeen duovigintillion three hundred seventeen unvigintillion seven hundred thirty-eight vigintillion two hundred fifty-two novemdecillion nine hundred octodecillion three hundred sixty-one septendecillion eighty-eight sexdecillion three hundred thirty-two quattuordecillion six hundred ninety-three tredecillion two hundred eighty-six duodecillion four hundred fifty-two undecillion nine hundred seventy-five decillion two hundred seventy-five nonillion five hundred twenty-five octillion one hundred thirty-eight septillion four hundred thirty-nine sextillion three hundred thirty-two quintillion six hundred forty-seven quadrillion six hundred two trillion two hundred ninety-eight billion two hundred fifty million six hundred thirty-three thousand one hundred thirty-nine'
    assert str(IntegerToEnglishLatin(2364641963025598692396925869239125822556498016441950523723059805522502416046135013136376310504248525502)) == 'two tretrigintillion three hundred sixty-four duotrigintillion six hundred forty-one untrigintillion nine hundred sixty-three trigintillion twenty-five novemvigintillion five hundred ninety-eight octovigintillion six hundred ninety-two septenvigintillion three hundred ninety-six sexvigintillion nine hundred twenty-five quinvigintillion eight hundred sixty-nine quattuorvigintillion two hundred thirty-nine trevigintillion one hundred twenty-five duovigintillion eight hundred twenty-two unvigintillion five hundred fifty-six vigintillion four hundred ninety-eight novemdecillion sixteen octodecillion four hundred forty-one septendecillion nine hundred fifty sexdecillion five hundred twenty-three quindecillion seven hundred twenty-three quattuordecillion fifty-nine tredecillion eight hundred five duodecillion five hundred twenty-two undecillion five hundred two decillion four hundred sixteen nonillion forty-six octillion one hundred thirty-five septillion thirteen sextillion one hundred thirty-six quintillion three hundred seventy-six quadrillion three hundred ten trillion five hundred four billion two hundred forty-eight million five hundred twenty-five thousand five hundred two'
    print('Tests passed')
